version: "2"

services:

  picocms:
    restart: always
    build: .
    image: thomastuerk/picocms:latest
    ports:
      - 8080:80
    environment:
      - INSTALL_PICOCMS=YES
      - N_UID=1000
      - N_GID=1000
    volumes:
      - ./picocms:/var/www/picocms

