#!/usr/bin/with-contenv bash

filename=`basename "$0"`

if [ ! -f $NGINX_PID_FILE ]; then
    echo "[cont-init.d] $filename: nginx pid file does not exist yet....Creating $NGINX_PID_FILE"
    mkdir -p $(dirname $NGINX_PID_FILE)
    touch $NGINX_PID_FILE
fi
