#!/usr/bin/with-contenv bash

##
# This script uses clever heredoc hack to substitute env variables into static config files
# Source: http://stackoverflow.com/questions/2914220/bash-templating-how-to-build-configuration-files-from-templates-with-bash
##

filename=`basename "$0"`

echo "[cont-init.d] $filename: substituting env vars into nginx configuration files..."

# Nginx doesn't support env variables in config files so we will have to do this in hacky way instead
VARS='$PORT:$WEB_ROOT:$NGINX_MAX_BODY_SIZE:$NGINX_FASTCGI_TIMEOUT:$WEB_USER:$WEB_GROUP'
envsubst "$VARS" < /etc/nginx/nginx.conf > /tmp/nginx.conf
mv /tmp/nginx.conf /etc/nginx/nginx.conf