#!/usr/bin/with-contenv bash

filename=`basename "$0"`

if [ "$INSTALL_PICOCMS" = "YES" ]; then 
    cp -r /opt/picocms/* $WEB_ROOT
    echo "[cont-init.d] $filename: copying PicoCMS files to $WEB_ROOT"
else
    echo "[cont-init.d] $filename: skipped copying PicoCMS files to $WEB_ROOT"
fi
